# Setup

In [1]:
import csv
import os
import glob

import pandas as pd

# Parse Data

In [ ]:
path = r'../../../data/src/rate-beer/reviews/'
allFiles = glob.glob(path + "/*.csv")
frame = pd.DataFrame()
list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0)
    list_.append(df)
frame = pd.concat(list_)

In [3]:
frame.head()

,Unnamed: 0,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,_has_fetched,abv,beer_id,brewed_at,brewery,...,street,style,style_rating,style_url,tags,telephone,type,url,web,weighted_avg
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,402.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,627.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,708.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN